import type { Category, LocalizedText } from '../types'

export const languageCopy = {
  de: {
    eyebrow: 'Senior Interview Trainer',
    title: '148 Fragen für JS, TS, React, Tooling, Architektur & OWASP',
    subtitle: 'Trainiere typische Senior-Level-Interviewfragen zu JavaScript, TypeScript, React sowie Tooling-, Pattern-, Architektur- und OWASP-Security-Themen.',
    searchLabel: 'Suche',
    searchPlaceholder: 'Nach Thema, Begriff oder Konzept suchen',
    reveal: 'Antwort anzeigen',
    revealed: 'Antwort sichtbar',
    explanation: 'Ausführliche Erklärung',
    resources: 'Weiterführende Quellen',
    questionList: 'Fragenkatalog',
    progress: 'Fortschritt',
    shown: 'Angezeigt',
    solved: 'Aufgedeckt',
    next: 'Nächste Frage',
    previous: 'Vorherige Frage',
    of: 'von',
    all: 'Alle',
    empty: 'Keine Fragen passen zum aktuellen Filter.',
    prompt: 'Wähle links eine Frage oder gehe mit den Navigationstasten durch den Katalog.',
    language: 'Sprache',
    answer: 'Kurzantwort',
    example: 'Beispiel',
    collapseCatalog: 'Katalog einklappen',
    expandCatalog: 'Katalog ausklappen',
    selected: 'Aktiv',
    marked: 'Markiert',
    markedOnly: 'Nur markierte',
    markQuestion: 'Frage markieren',
    unmarkQuestion: 'Markierung entfernen',
    openResource: 'Quelle öffnen',
    lockedPrompt: 'Die Karte bleibt bis zum Klick absichtlich zugeklappt, damit du die Antwort zuerst selbst formulierst.',
    emptyDetail: 'Passe Suche, Kategorie oder Markierungsfilter an, um wieder eine aktive Frage anzuzeigen.',
    loadingQuestions: 'Fragen werden geladen',
    loadingDescription: 'Der Fragenkatalog wird als eigener Chunk geladen, damit die App schneller startet.',
    loadErrorTitle: 'Fragen konnten nicht geladen werden',
    loadErrorDescription: 'Bitte lade die Seite neu. Wenn das Problem bleibt, prüfe den Build oder die Netzwerk-Konsole.',
  },
  en: {
    eyebrow: 'Senior Interview Trainer',
    title: '148 questions for JS, TS, React, tooling, architecture, and OWASP',
    subtitle: 'Practice senior-level interview prompts on JavaScript, TypeScript, React, and broader tooling, pattern, architecture, and OWASP security topics.',
    searchLabel: 'Search',
    searchPlaceholder: 'Search by topic, term, or concept',
    reveal: 'Reveal answer',
    revealed: 'Answer visible',
    explanation: 'Detailed explanation',
    resources: 'Further reading',
    questionList: 'Question bank',
    progress: 'Progress',
    shown: 'Shown',
    solved: 'Revealed',
    next: 'Next question',
    previous: 'Previous question',
    of: 'of',
    all: 'All',
    empty: 'No questions match the current filter.',
    prompt: 'Pick a question from the left or use the navigation buttons to move through the bank.',
    language: 'Language',
    answer: 'Short answer',
    example: 'Example',
    collapseCatalog: 'Collapse catalog',
    expandCatalog: 'Expand catalog',
    selected: 'Active',
    marked: 'Marked',
    markedOnly: 'Marked only',
    markQuestion: 'Mark question',
    unmarkQuestion: 'Remove mark',
    openResource: 'Open resource',
    lockedPrompt: 'The card stays intentionally closed until you click, so you can formulate your own answer first.',
    emptyDetail: 'Adjust the search, category, or marked filter to bring an active question back.',
    loadingQuestions: 'Loading questions',
    loadingDescription: 'The question bank loads as a separate chunk so the app can start with less initial JavaScript.',
    loadErrorTitle: 'Questions could not be loaded',
    loadErrorDescription: 'Reload the page. If the problem persists, inspect the build output or the network console.',
  },
} as const

export type UiCopy = {
  [Key in keyof (typeof languageCopy)['de']]: string
}

export const categoryLabels: Record<Category, LocalizedText> = {
  javascript: { de: 'JavaScript', en: 'JavaScript' },
  typescript: { de: 'TypeScript', en: 'TypeScript' },
  react: { de: 'React', en: 'React' },
  toolingArchitecture: {
    de: 'Tooling, Patterns & Architektur',
    en: 'Tooling, Patterns & Architecture',
  },
  owasp: {
    de: 'OWASP',
    en: 'OWASP',
  },
}

export const categoryOrder = ['javascript', 'typescript', 'react', 'toolingArchitecture', 'owasp'] as const
